from typing import Any, Optional, Protocol, runtime_checkable


@runtime_checkable
class RegistryStore(Protocol):
    def ping(self) -> bool: ...

    def find_session_by_task(self, task_id: str) -> Optional[str]: ...

    def save_session(self, task_id: str, document: dict[str, Any]) -> str: ...

    def get_session(self, session_id: str) -> Optional[dict[str, Any]]: ...

    def list_session_ids(self, *, skip: int = 0, limit: int = 50) -> list[str]: ...

    def count_sessions(self) -> int: ...

    def list_session_documents(self, *, skip: int = 0, limit: int = 50) -> list[dict[str, Any]]: ...

    def save_document(self, session_id: str, document: dict[str, Any]) -> None: ...

    def list_published_ids(self, *, skip: int = 0, limit: int = 50) -> list[str]: ...

    def set_published(self, session_id: str, published: bool) -> None: ...

    def save_user(self, user: dict[str, Any]) -> str: ...

    def get_user(self, user_id: str) -> Optional[dict[str, Any]]: ...

    def get_user_by_username(self, username: str) -> Optional[dict[str, Any]]: ...

    def list_users(self) -> list[dict[str, Any]]: ...

    def delete_user(self, user_id: str) -> bool: ...

    def update_user_fields(self, user_id: str, updates: dict[str, Any]) -> dict[str, Any] | None: ...
